//LOCALHOST

GET http://localhost:8080/hobbies
###

GET http://localhost:8080/hobbies/63dd6651c5dff5487828f8ba

###
POST http://localhost:8080/hobbies HTTP/1.1
content-type: application/json

{
"name":"dance", 
"description":"Dancing is one of the hobbies on this list of hobbies that de-stresses you and calms your anxiety.", 
"benefit":"It is one of the examples of hobbies to get in shape and improve your self-esteem."
 
}

###
PUT http://localhost:8080/hobbies/63dd6651c5dff5487828f8bb  HTTP/1.1
content-type: application/json

{
"name":"PlayVideoGames", 
"description":"The majority of people see gaming as a hobby that is entertaining, sociable and a way to wind down. It is one of several interests and activities in their life alongside spending time with friends and family, going to school or work, and their daily responsibilities.", 
"benefit":"Gaming can offer many more benefits than other hobbies and pastimes. It is a safe space to fail, build resilience, overcome challenges and explore alternative identities through characters and in-game worlds."
 
}

###
DELETE http://localhost:8080/hobbies/63dd893c97f29ba9b5d61e04 HTTP/1.1
content-type: application/json

