//LOCALHOST

GET http://localhost:8080/hobbies
###

GET http://localhost:8080/hobbies/63dd6651c5dff5487828f8b9

###
POST http://localhost:8080/hobbies HTTP/1.1
content-type: application/json

{
"name":"read", 
"description":"Reading is one of the examples of ideal hobbies for traveling and training the brain at the same time. With one of the fun hobbies", 
"benefit":"You are transported to other places, you exercise your memory and your creativity, you improve your concentration and you become more empathetic!"
 
}

###
PUT http://localhost:8080/hobbies/63dd6651c5dff5487828f8bb  HTTP/1.1
content-type: application/json

{
"name":"PlayVideoGames", 
"description":"The majority of people see gaming as a hobby that is entertaining, sociable and a way to wind down. It is one of several interests and activities in their life alongside spending time with friends and family, going to school or work, and their daily responsibilities.", 
"benefit":"Gaming can offer many more benefits than other hobbies and pastimes. It is a safe space to fail, build resilience, overcome challenges and explore alternative identities through characters and in-game worlds."
 
}

###
DELETE http://localhost:8080/hobbies/63dd6651c5dff5487828f8bb HTTP/1.1
content-type: application/json

